monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        app:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_app.log"
            level: debug
            channels: ["app"]
        messenger:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_messenger.log"
            level: debug
            channels: ["messenger"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        deprecation:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            max_files: 10
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error
            handler:    grouped
        grouped:
            type: group
            #members: [syslog_handler,deduplicated]
            members: [syslog_handler]
        #deduplicated:
            #type:    deduplication
            #handler: symfony_mailer
        #symfony_mailer:
            #type:       symfony_mailer
            #from_email: '%env(resolve:CONTACT_MAIL)%'
            #to_email:   '%env(resolve:CONTACT_MAIL)%'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            #subject:    '[%env(resolve:MAIL_SUBJECT)%] An Error Occurred!'
            #level:      info
            #formatter:  monolog.formatter.html
            #content_type: text/html