#!/bin/sh
# When assume the certificate is renewed on XX server
# Replace XX and user with the appropriate values
# Make sure to have SSH keys set up for passwordless authentication

# Add in your crontab (/etc/crontab)
# Every 16th day of the month at 02:02 AM
# 02 02   16 * *  root    /etc/apache2/update-cert

scp user@XX:/home/user/cert-remotelabz/* /etc/apache2/
cp /etc/apache2/RemoteLabz-WebServer.key /etc/ssl/private/privkey.pem
cp /etc/apache2/RemoteLabz-WebServer.crt /etc/ssl/certs/fullchain.pem

service apache2 restart
#service remotelabz-worker restart
