# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.install.directory: '%kernel.project_dir%'
    app.worker.ip: '%env(resolve:WORKER_IP)%'
    app.network.lab.interface: '%env(resolve:ADM_INTERFACE)%'
    app.network.lab.cidr: '%env(resolve:LAB_NETWORK)%'
    app.network.data.interface: '%env(resolve:DATA_INTERFACE)%'
    app.network.data.cidr: '%env(resolve:DATA_NETWORK)%'
    app.serverssh: '%env(resolve:SERVER_SSH)%'
    app.pdu.api.login: '%env(resolve:PDU_API_LOGIN)%'
    app.pdu.api.password: '%env(resolve:PDU_API_PASSWORD)%'
    app.network.lab.internet_interface: '%env(string:INTERNET_INTERFACE_ACCESS)%'
    app.data.network.interface.ip: '%env(resolve:DATA_INT_IP_ADDRESS)%'
    app.data.network.gateway: '%env(resolve:DATA_INT_GW)%'
    app.services.proxy.wss: '%env(bool:REMOTELABZ_PROXY_USE_WSS)%'
    app.services.proxy.cert: '%env(string:REMOTELABZ_PROXY_SSL_CERT)%'
    app.services.proxy.key: '%env(string:REMOTELABZ_PROXY_SSL_KEY)%'
    app.vpn.interface: '%env(string:VPN_CONCENTRATOR_INTERFACE)%'
    app.network.front.ip: '%env(string:FRONT_SERVER_IP)%'
    app.general.contact_mail: '%env(resolve:CONTACT_MAIL)%'
    app.lxc.default_mindiskspace: '%env(resolve:DEFAULT_MIN_DISKSPACE_LXC)%'
    app.ssh.worker.user : '%env(resolve:SSH_USER_WORKER)%'
    app.ssh.worker.passwd : '%env(resolve:SSH_USER_WORKER_PASSWD)%'
    app.ssh.worker.privatekey : '%env(resolve:SSH_USER_PRIVATEKEY_FILE)%'
    app.ssh.worker.publickey : '%env(resolve:SSH_USER_PUBLICKEY_FILE)%'
    app.ssh.front.user: '%env(resolve:SSH_USER_FRONT)%'
    app.ssh.front.passwd: '%env(resolve:SSH_USER_FRONT_PASSWD)%'


services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\Instance\InstanceManager:
        arguments:
            $front_ip: '%app.network.front.ip%'
            $server_ssh: '%app.serverssh%'
            $pdu_api_login: '%app.pdu.api.login%'
            $pdu_api_password: '%app.pdu.api.password%'
            $sshPublicKey: '%app.ssh.worker.publickey%'
            $sshPrivateKey: '%app.ssh.worker.privatekey%'
            $sshUser: '%app.ssh.front.user%'
            $sshPasswd: '%app.ssh.front.passwd%'
            $install_directory: '%app.install.directory%'       

    App\Service\ResourcesCacheService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\CachedStateController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\EventSubscriber\WorkerStartedEventSubscriber:
        arguments:
            $worker_ip: '%app.worker.ip%'